sesm00-hw12
nvbach91/4IZ268-2021-2022-ZS pull request #102
Opened 2021-12-14 14:37 UTC by sesm00

Odevzdávám domácí úkol č.10
[https://eso.vse.cz/~sesm00/cv12/homework/](https://eso.vse.cz/~sesm00/cv12/homework/)

2021-12-22 09:42 UTC, nvbach91 requested changes

2021-12-22 09:42 UTC, nvbach91 commented on www/sesm00/hw12/js/main.js
> +  body.on('click', '#search-form button', function (event) {
lepsi `form.submit()`, musi to byt

2021-12-22 09:42 UTC, nvbach91 commented on www/sesm00/hw12/js/main.js
> +  function drawResults() {
renderResults

2021-12-23 09:56 UTC, sesm00 commented on www/sesm00/hw12/js/main.js
> +  body.on('click', '#search-form button', function (event) {
fixed

2021-12-23 19:14 UTC, nvbach91 approved these changes

2021-12-23 19:14 UTC, merged