matj27-sp2
nvbach91/4IZ268-2021-2022-ZS pull request #120
Opened 2021-12-23 10:20 UTC by matj27-vse

Odkaz na aplikaci: https://eso.vse.cz/~matj27/sp2/

Pilotní verze

2022-01-05 22:41 UTC, matj27-vse commented
Semestrální práce připravená k odevzdání a obhajobě.
https://eso.vse.cz/~matj27/sp2/

2022-01-06 13:00 UTC, nvbach91 requested changes

2022-01-06 13:00 UTC, nvbach91 commented on www/matj27/sp2/js/app.js
> +    appDiv: $('#app'),
tohle musi byt v callbacku document ready

2022-01-06 13:00 UTC, nvbach91 commented on www/matj27/sp2/js/app.js
> + * Method for getting a parameter from url
metody se pojmenovavaji trosku jinak

2022-01-06 13:00 UTC, nvbach91 commented on www/matj27/sp2/js/app.js
> +    while (!appStructurePrepared) {
neni treba pretezovat browser aby timto zpusobem loopoval cekal na data, takhle nikdo nepouziva async await, ty slouzi predevsim pro Promisove objekty, lepsi by bylo to udelat interaktivne,

2022-01-06 13:00 UTC, nvbach91 commented on www/matj27/sp2/js/email-sender.js
> +        alert('Chyba pri generovani tela zpravy!');
nepouzivejter alert, ani confirm, pouzivejte modalova okna, napr. https://speckyboy.com/free-modal-window-libraries-plugins/

2022-01-07 14:29 UTC, nvbach91 approved these changes

2022-01-07 14:33 UTC, merged