trat16-sp2
nvbach91/4IZ268-2021-2022-ZS pull request #122
Opened 2021-12-23 14:15 UTC by mrtomis

Pilotní verze SP2 https://eso.vse.cz/~trat16/sp2/

2022-01-31 17:18 UTC, nvbach91 requested changes

2022-01-31 17:18 UTC, nvbach91 commented on www/trat16/sp2/assets/main.js
> +            $(".weather").slideDown(1000);
vsechny vysledky selektovani elementu, ktere se opakovane vybiraji, ukladejte do promenne a prepouzivejte je

2022-01-31 17:18 UTC, nvbach91 commented on www/trat16/sp2/assets/main.js
> +                src: "http://openweathermap.org/img/wn/" + icon + ".png",
vsechna zretezeni stringu prepiste do interpolace

2022-01-31 17:18 UTC, nvbach91 commented on www/trat16/sp2/assets/main.js
> +        fetchWeather: function (lat, lon, units) {
proc jsou funkce definovany uvnitr objektu?

2022-01-31 17:18 UTC, nvbach91 commented on www/trat16/sp2/assets/main.js
> +            weather.fetchWeather(localStorage.getItem('lat'), localStorage.getItem('lon'), "metric");
pro string používejte apotrofy

2022-01-31 17:18 UTC, nvbach91 commented on www/trat16/sp2/assets/main.js
> +let cache = {
lze tohle dat do document.ready?

2022-02-02 11:08 UTC, mrtomis commented on www/trat16/sp2/assets/main.js
> +            $(".weather").slideDown(1000);
A mám je dát do objektu cache nebo normálně jako proměnné v $(document).ready() ?

2022-02-02 11:11 UTC, mrtomis commented on www/trat16/sp2/assets/main.js
> +            $(".weather").slideDown(1000);
A mám je dát do objektu cache nebo normálně jako proměnné v $(document).ready()?

2022-02-04 14:16 UTC, nvbach91 approved these changes

2022-02-04 14:16 UTC, merged