doho01-sp2
nvbach91/4IZ268-2021-2022-ZS pull request #146
Opened 2021-12-24 18:20 UTC by AirbornBird88

Dobrý den, 
doufám, že jsem na žádný soubor nezapomněl.
Link to application: https://eso.vse.cz/~doho01/sp2/

přeji hezké svátky,
Do Viet Anh

2022-02-03 11:34 UTC, nvbach91 requested changes
nevim cim to je ale aplikace vubec nefunguje, vyhledavani sice neco ukazuje ale tlacitka nic nedelaji a kdyz kliknu na delete tak se dostanu na stranku eso.vse.cz

2022-02-03 13:16 UTC, AirbornBird88 commented
> nevim cim to je ale aplikace vubec nefunguje, vyhledavani sice neco ukazuje ale tlacitka nic nedelaji a kdyz kliknu na delete tak se dostanu na stranku eso.vse.cz

To je divné, ještě se na to mrknu

2022-02-03 13:27 UTC, AirbornBird88 commented
Už by to mělo fungovat. Místo reload() jsem dal  location.replace('https://eso.vse.cz/~doho01/sp2/');
Uploadnul jsem to znovu na server. Nicméně po kliknutí na stránku stále nevidím v js souboru mnou provedené změny. Nevím, jak funguje režim updatu na serveru. Proč se to neukládá hned.
Jinak mně tlačítka normálně fungují.

2022-02-03 13:35 UTC, AirbornBird88 commented
Než se ty změny promítnou na serveru eso.vse.cz, tak zde pro Vás uvedu základní onboarding:
1) Kliknete na mapu (kdekoliv), vytvoří se marker
2) Těch markerů můžete vytvořit víc (active marker is bouncing)
3) Dole se objeví tlačítko "Add note" , na to když kliknete, vytvoří se nová poznámka (notes)
4) Title a body dané poznámky můžete samozřejmě upravit (změny se promítnou po kliknutí jinam, tedy eventem je "blur")
5) Těch poznámek můžete přidat víc, stačí kliknutí na "Add note"
6) Též můžete vyhledávat místa, k tomu slouží input vlevo dole ("Please enter location") 
7) Vpravo jsou tlačítka (doufám, že už fungují)
a další...

2022-02-04 14:12 UTC, nvbach91 approved these changes

2022-02-04 14:12 UTC, merged