jocv00-sp2
nvbach91/4IZ268-2021-2022-ZS pull request #168
Opened 2021-12-31 08:48 UTC by jochimv

Odkaz na sp2: https://eso.vse.cz/~jocv00/sp2/

2022-01-06 12:35 UTC, nvbach91 requested changes

2022-01-06 12:35 UTC, nvbach91 commented on www/jocv00/sp2/js/app.js
> +    return navigator.onLine;
![image](https://user-images.githubusercontent.com/20724910/148383599-f8fe0967-d1d9-4229-a5e9-a3b399e93949.png)

2022-01-06 12:35 UTC, nvbach91 commented on www/jocv00/sp2/js/app.js
> +    return navigator.onLine;
https://www.npmjs.com/package/offline-js

2022-01-06 12:43 UTC, nvbach91 commented on www/jocv00/sp2/js/app.js
> +    main.append(container);
nesmite modifikovat DOM v cyklu

2022-01-08 00:32 UTC, jochimv commented on www/jocv00/sp2/js/app.js
> +    return navigator.onLine;
Nefunguje - request na soubor projektu projde i bez internetového připojení, request na externí soubor zase neprojde nikdy z důvodu blokace CORS policy.

2022-01-08 00:33 UTC, jochimv commented on www/jocv00/sp2/js/app.js
> +    main.append(container);
Ponechávám tak z důvodu nedostatku času na jiné zkoušky.

2022-01-08 00:34 UTC, jochimv commented
Zapracována obhajoba, změny jsou i na serveru.

2022-01-08 00:34 UTC, jochimv commented
Zapracována obhajoba, změny jsou i na serveru

2022-01-08 11:54 UTC, nvbach91 approved these changes

2022-01-08 11:54 UTC, merged